apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vellozap-food-service
  namespace: vellozap-food
  labels:
    app.kubernetes.io/part-of: arcobatrox
spec:
  secretName: vellozap-food-service-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: api.vellozap-food.arcobatrox.com.br
  dnsNames:
    - api.vellozap-food.arcobatrox.com.br
    - www.api.vellozap-food.arcobatrox.com.br
